#!/usr/bin/env bash
# Creates a custom 404 not found error_page for nginx

# Check if nginx is already installed or not
IS_INSTALLED=$(apt list --installed | grep -c nginx)

if [ "$IS_INSTALLED" == 0 ]; then
    # Installing nginx
    sudo apt update -y
    sudo apt install -y nginx
fi

# Add the 404 page
if ! [ -f /var/www/html/404.html ]; then
    cat > 404.html << EOF
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        Ceci n'est pas une page
    </body>
    </html>
EOF
    sudo mv 404.html /var/www/html/
fi

# Configure nginx to show the page
if [ -f /etc/nginx/sites-available/default ]; then
    sudo sed -i '41a\
        error_page 404 /404.html;\
        location = /404.html {\
            root /var/www/html;\
            internal;\
        }' /etc/nginx/sites-available/default
fi

sudo service nginx restart
