#!/usr/bin/env bash
# Creates a custom 404 not found error_page for nginx

# Check if nginx is already installed or not
IS_INSTALLED=$(apt list --installed | grep -c nginx)

if [ "$IS_INSTALLED" == 0 ]; then
    # Installing nginx
    sudo apt update -y
    sudo apt install -y nginx
fi

# Add the 404 page
if ! [ -f /var/www/html/404.html ]; then
    echo "Ceci n'est pas une page" > 404.html
    sudo mv 404.html /var/www/html/
fi

# Configure nginx to show the page
if [ -f /etc/nginx/sites-available/default ]; then
    cat > error_page << EOF
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }

EOF
    export CONFIG=$(cat error_page)
    rm error_page
    sudo sed -i "54 a $CONFIG" /etc/nginx/sites-available/default
fi

sudo service nginx restart
