#!/usr/bin/env bash
# Configure a brand new Ubuntu machine to the requirements asked in this task

# Check if nginx is already installed or not
IS_INSTALLED=$(apt list --installed | grep -c nginx)

if [ "$IS_INSTALLED" == 0 ]; then
    # Installing nginx
    sudo apt update -y
    sudo apt install -y nginx
fi

# Create redirect page
chown -R ubuntu /var/www
if ! [ -f /var/www/html/index.html ]; then
    cat > index.html << EOF
    Hello World!
EOF
    sudo mv index.html /var/www/html/
fi

# Add the 404 page
if ! [ -f /var/www/html/404.html ]; then
    cat > 404.html << EOF
    Ceci n'est pas une page
EOF
    sudo mv 404.html /var/www/html/
fi

# Configure nginx to show the pages
if [ -f /etc/nginx/sites-available/default ]; then

    # Configuration for redirect page
    sudo sed -i '24a\
        rewrite ^/redirect_me https://github.com/YehiaMedhat000 permanent;' /etc/nginx/sites-available/default

    # Configuration for the 404 NOT FOUND error page
    sudo sed -i '41a\
        error_page 404 /404.html;\
        location = /404.html {\
            root /var/www/html;\
            internal;\
        }\
' /etc/nginx/sites-available/default

    # Add the upstream backend block
    sudo sed -i "24a\
    \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

fi

sudo nginx -t
sudo service nginx restart
