#!/usr/bin/env bash
# Prints number from 1-20 with some phrases
HOURS=0
while [ $HOURS -le 12 ]; do
	echo "Hour: $HOURS"
	MINS=1
	while [ $MINS -le 59 ]; do
		echo $MINS
		MINS=$(( MINS + 1 ))
	done
	HOURS=$(( HOURS + 1 ))
done;
