#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

echo "127.0.0.2 localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
