#!/bin/bash
# Creates an rsa key pair for connection

# Define variables
KEY_NAME="school"
KEY_BITS="4096"
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b ${KEY_BITS} -f ${KEY_NAME} -N ${PASSPHRASE}
